name: Build Multi-Platform Executables

on: [push]

jobs:

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual
      - name: Check out repository code
        uses: actions/checkout@v3

      # 2. Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      # 3. Instala as dependências (PyInstaller e outras do seu projeto)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # 4. Roda o PyInstaller para criar o .exe
      - name: Build with PyInstaller
        run: pyinstaller --onefile --name "MeuAppWindows" main.py

      # 5. Faz o upload do executável como um "artefato" para download
      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable 
          path: dist/MeuAppWindows.exe

  # --- JOB PARA MACOS ---
  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual
      - name: Check out repository code
        uses: actions/checkout@v3

      # 2. Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Instala as dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # 4. Roda o PyInstaller para criar o executável do Mac
      - name: Build with PyInstaller
        run: pyinstaller --onefile --name "MeuAppMac" main.py 

      # 5. Faz o upload do executável como um "artefato" para download
      - name: Upload macOS executable
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable 
          path: dist/MeuAppMac